language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

script:
  - cmake --version
  - mkdir build && cd build
  - cmake -DBUILD_TESTS=ON -DBUILD_SAMPLE=ON .. || exit $?
  - cmake --build . || exit $?
  - ctest --verbose || exit $?
  - ./squash_sample || exit $?
